# Generated by Django 6.0.4 on 2026-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_orderitem_order_remove_orderitem_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller_product',
            name='unit_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('ml', 'ML'), ('gm', 'Gram')], default='tablet', max_length=20),
        ),
    ]
