# Generated by Django 6.0.4 on 2026-04-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_product_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='seller_Product',
        ),
    ]
