# Generated by Django 6.0.4 on 2026-04-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_seller_product_brand_seller_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
