# Generated by Django 6.0.4 on 2026-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_seller_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
