# Generated by Django 6.0.4 on 2026-04-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_seller_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('uses', 'Uses'), ('dosage', 'Dosage'), ('side_effects', 'Side Effects'), ('warnings', 'Warnings'), ('precautions', 'Precautions'), ('interactions', 'Interactions'), ('storage', 'Storage'), ('quick_tips', 'Quick Tips'), ('faq', 'FAQs'), ('lifestyle', 'Lifestyle Recommendation')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('product_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='admin_panel.seller_product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='admin_panel.productcontent')),
            ],
        ),
    ]
