# Generated by Django 5.2.8 on 2026-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(max_length=700)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category_image',
            new_name='category_image',
        ),
    ]
