# Generated by Django 5.2.8 on 2026-04-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_faq_rename_category_image_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='faq_answer',
            field=models.TextField(default='No answer available'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_question',
            field=models.CharField(max_length=300),
        ),
    ]
