# Generated by Django 5.2.8 on 2026-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_faq_faq_answer_alter_faq_faq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_answer',
            field=models.TextField(blank=True),
        ),
    ]
