# Generated by Django 6.0.4 on 2026-05-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('ml', 'ML'), ('gm', 'Gram')], default='tablet', max_length=20),
        ),
    ]
